#!/bin/bash

set -e

## Some simple sanity checks for code quality in infrastructure

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DIR="$SCRIPT_DIR/.."
cd "$DIR"

# Markdown
markdown-link-check "README.md"
markdown-link-check "research.md"

# Python
black --diff "etc/dafnydep"
mypy "etc/dafnydep"
mypy etc/*.py
black --diff etc/*.py eval/*.py
pytest etc

# Bash
shellcheck "etc/dafnyq"
shellcheck "etc/check"

# Go
echo "gofmt"
gofmt -d nfsd dafny_go
echo "go vet"
go vet ./nfsd/... ./dafny_go/...
