#!/usr/bin/env python3

import sys
from timing import parse_df


def main():
    df = parse_df(sys.stdin)
    print(df.sort_values(by="time_s", ascending=False).head(10))
    total_s = df.time_s.sum()
    print(f"total: {total_s:0.2f}")


if __name__ == "__main__":
    main()
